apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cntk-sonarqube
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cntk
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/cntk/sonarqube
    repoURL: https://github.com/cloud-native-toolkit-test/provider-test-0v2i9s.git
    targetRevision: main
    helm:
      releaseName: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
